### ISSUE TITLE
wht's FCD?

### ISSUE THREAD

**Issue by ake020675** [walty19950301/CDA-contour-optimizer#1]
NO defination of Fcd in GOP.detect()?

**Comment by ake020675** [comment]
according to the paper, "FCD is the result of CDA".
However, it should be initialized before it's used in detect(), right?

**Comment by walty19950301** [comment]
Yes, it should be generated by a ChangeDetectionAlgorithm (CDA). For example ViBe, FgSegNet_v2, GMM, etc.
Detect () is an optimizer function, That optimizes the result of the CDA.

```
cv::Mat frame;
cv::VideoCapture cap("xxxx.mp4");
wq::GOP gop;
ViBe vibe;
frame << cap;
vibe.init(frame);
gop.init(frame);
while(true){
  frame << cap;
  if (frame.empty()) {
    break;
  }
  cv::Mat result = vibe.process(frame); // Get binary mat. (every pixel should be 1 or 0)
  result = gop.detect(frame, result); 
  // cv::imshow("xxx", result); cv::waitKey(1);
}
```

**Comment by walty19950301** [comment]
I will update more detail about how to call the optimizer next weekend.
Thanks for your attention~ (^_^)

**Comment by ake020675** [comment]
Got it! Thanks for reply
